options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','ananthweb:v1', '.' ]
  # Run container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run','-itd', '--name','anantha','-p','8081:80','--rm','ananthweb:v1']
  # test curl
  - name: 'ubuntu'
    args: ['curl','http://localhost:8081/health.html']