options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','ananthweb:v1', '.' ]
  # Scan image
  - name: 'aquasec/trivy:latest'
    args: ['image' ,'--severity' ,'HIGH,CRITICAL' ,'--format', 'json',  '--output' , '/workspace/anantha_imagescan.json','--exit-code', '0', 'ananthweb:v1']
  # Save result in GCS
  - name: 'google/cloud-sdk'
    args: ['gsutil','cp','/workspace/anantha_imagescan.json','gs://anantha_voda_devsecops/trivy_scan_result']
  # Run container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run','-itd', '--name','anantha','-p','8081:80','--rm','ananthweb:v1']
  # health check
  - name: 'gcr.io/cloud-builders/docker'
    args: ['exec','anantha','curl','-f','http://localhost/health.html']
