apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: anantha-app-deploy
  name: anantha-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anantha-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: anantha-app-deploy
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/vodafone-devsecops/anantha-image-registry/ananthweb:v1
        name: cont-anantha
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
status: {}
